export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const SET_TABLE_PAGINATION = 'SET_TABLE_PAGINATION';
export const SET_TABLE_SORTER = 'SET_TABLE_SORTER';
export const SET_TABLE_TOTAL = 'SET_TABLE_TOTAL';
export const SET_TABLE_SEARCH = 'SET_TABLE_SEARCH';
